import localFont from 'next/font/local';

import Header from '@/components/Header';

import type { Metadata } from 'next';
import './globals.css';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} min-h-dvh w-full`}>
        <Header />
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
